#!/usr/bin/env python3
"""Generate AppColors.h from Palette.js (single source of truth).

5WHY (2026-08-17): AppColors.h and Palette.js were hand-maintained mirrors —
a color change in one toolchain silently diverged from the other
(verified example: dark textMuted was #64748B in AppColors.h but #8494A8 in
Palette.js).  This generator derives all M3 role macros from Palette.js.
Report-only colors (APPC_REPORT_*, CSS accents, progress) are not theme
tokens — they live in a static template block below.  The status RGB macros
(APPC_*_RGB) are DERIVED from the palette (5WHY 2026-08-17 review: they were
hand-maintained literals mirroring the status roles and drifted silently).

Usage:
  python3 scripts/generate-appcolors.py            # write AppColors.h
  python3 scripts/generate-appcolors.py --check    # fail if the file drifted
"""
# 5WHY (review 2026-08-17): future-annotations 使注解惰性化，兼容 3.8/3.9
# （macOS 自带 python3 = 3.9）。
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from palette_common import parse_palette, read_palette

ROOT = Path(__file__).resolve().parent.parent
APP_COLORS = ROOT / "src/Common/Utils/AppColors.h"

# (macro stem, palette key) — every M3 role × {dark, light}
ROLES = [
    ("PRIMARY", "primary"),
    ("ON_PRIMARY", "onPrimary"),
    ("PRIMARY_CONTAINER", "primaryContainer"),
    ("SECONDARY", "secondary"),
    ("ON_SECONDARY", "onSecondary"),
    ("TERTIARY", "tertiary"),
    ("ON_TERTIARY", "onTertiary"),
    ("ERROR", "error"),
    ("ON_ERROR", "onError"),
    ("SURFACE", "surface"),
    ("ON_SURFACE", "onSurface"),
    ("ON_SURFACE_VARIANT", "onSurfaceVariant"),
    ("SURFACE_CONTAINER_LOW", "surfaceContainerLow"),
    ("SURFACE_CONTAINER", "surfaceContainer"),
    ("SURFACE_CONTAINER_HIGHEST", "surfaceContainerHighest"),
    ("OUTLINE", "outline"),
    ("OUTLINE_VARIANT", "outlineVariant"),
    ("ACCENT", "accent"),
    ("TEXT_PLACEHOLDER", "textPlaceholder"),
    ("SUCCESS", "success"),
    ("WARNING", "warning"),
    ("WARNING_STRONG", "warningStrong"),
    ("FAIL", "fail"),
    ("SKIP", "skip"),
    ("INFO", "info"),
    ("TERMINAL_TEXT", "terminalText"),
    ("ON_SUCCESS_CONTAINER", "onSuccessContainer"),
    ("ICON_INK", "iconInk"),
    ("ON_FAIL", "onFail"),
    ("ON_ACCENT_PAD", "onAccentPad"),
]

# Stem→key lookup built once (5WHY review 2026-08-17: dict(ROLES) was rebuilt
# inside macro_line per call — 78 throwaway 39-entry dicts per run).
ROLES_MAP = dict(ROLES)
# palette-key set for the ROLES↔Palette.js cross-validation below.
ROLES_KEYS = set(ROLES_MAP.values())

HEADER = """// =============================================================================
// AppColors.h — M3 semantic color roles (single source of truth for C++ colors)
//
// AUTO-GENERATED by scripts/generate-appcolors.py from
//   src/Common/View/theme/Palette.js — DO NOT EDIT THIS FILE.
//   Naming conventions are identical between C++ and QML:
//     C++:  APPC_PRIMARY_DARK / APPC_PRIMARY_LIGHT
//     QML:  Palette.Dark.primary / Palette.Light.primary
//
// Architecture (2026-08-17 M3 rename + simplify): Material 3 color roles —
//   primary/secondary/tertiary/error with on-* text pairs, surface + three
//   container levels, outline vs outlineVariant — plus NetDiagnostics
//   extended tokens.  Zero-consumer roles are deliberately absent (simplify
//   round 2026-08-17).  Exception: terminalText/onSuccessContainer are
//   QML-side semantic tokens tracked here for Palette.js↔AppColors.h sync
//   (a QML token leaving the sync net caused the dark textMuted divergence).
//   Color VALUES are unchanged from the pre-M3 palette —
//   5WHY: visual parity is a hard requirement of the rename; contrast
//   deviations are tracked by scripts/audit-palette-contrast.py instead of
//   being fixed here.
//
// KNOWN DEVIATION (pre-existing, report-local): APPC_TEXT_MUTED_* is #64748B
//   and intentionally NOT synced with Palette.js dark textMuted (#8494A8) —
//   the HTML report keeps its contrast-tuned text color.  Verified by
//   cmake/VerifyPaletteSync.cmake which deliberately skips textMuted.
// =============================================================================
#pragma once
"""

TAIL = """// ═══════════════════════════════════════════════════════════════════════════════
// REPORT-SPECIFIC COLORS (HTML/PDF report generation — report-local, static)
// ═══════════════════════════════════════════════════════════════════════════════

// ── Report-local text levels (see KNOWN DEVIATION header note) ────────────────
#define APPC_TEXT_MUTED_DARK           "#64748B"
#define APPC_TEXT_MUTED_LIGHT          "#64748B"

// ── Dark report theme ─────────────────────────────────────────────────────────
#define APPC_REPORT_DARK_BG_HEADER   "#0C4A6E"
#define APPC_REPORT_DARK_BG_SECTION  "#1E293B"
#define APPC_REPORT_DARK_BG_ROW_ALT  "#1E293B"
#define APPC_REPORT_DARK_BG_ROW      "#0F172A"
#define APPC_REPORT_DARK_BG_CARD_PASS "#16281b"
#define APPC_REPORT_DARK_BG_CARD_INFO "#141f33"
#define APPC_REPORT_DARK_BG_CARD_WARN "#2b2810"
#define APPC_REPORT_DARK_BG_CARD_FAIL "#2b1616"
#define APPC_REPORT_DARK_BG_CARD_SKIP "#1e1e2e"
#define APPC_REPORT_DARK_BORDER       "#334155"
#define APPC_REPORT_DARK_CODE_BG      "#0a0a14"
#define APPC_REPORT_DARK_CODE_FG      "#c0c0d0"
#define APPC_REPORT_DARK_DETAIL_BG    "#0f1629"
#define APPC_REPORT_DARK_FOOTER       "#5a5a72"
#define APPC_REPORT_DARK_HEADER_TARGET "#E2E8F0"
#define APPC_REPORT_DARK_HEADER_META  "#94A3B8"

// ── Light report theme ────────────────────────────────────────────────────────
#define APPC_REPORT_LIGHT_BG_HEADER  "#0F172A"
#define APPC_REPORT_LIGHT_BG_SECTION "#0F172A"
#define APPC_REPORT_LIGHT_BG_ROW_ALT "#F8FAFC"
#define APPC_REPORT_LIGHT_BG_ROW     "#FFFFFF"
#define APPC_REPORT_LIGHT_BG_CARD_PASS "#ECFDF5"
#define APPC_REPORT_LIGHT_BG_CARD_INFO "#EFF6FF"
#define APPC_REPORT_LIGHT_BG_CARD_WARN "#FFFBEB"
#define APPC_REPORT_LIGHT_BG_CARD_FAIL "#FEF2F2"
#define APPC_REPORT_LIGHT_BG_CARD_SKIP "#F1F5F9"
#define APPC_REPORT_LIGHT_BORDER      "#E2E8F0"
#define APPC_REPORT_LIGHT_CODE_BG     "#0F172A"
#define APPC_REPORT_LIGHT_CODE_FG     "#E2E8F0"
#define APPC_REPORT_LIGHT_DETAIL_BG   "#F8FAFC"
#define APPC_REPORT_LIGHT_FOOTER      "#94A3B8"
#define APPC_REPORT_LIGHT_HEADER_TARGET "#E2E8F0"
#define APPC_REPORT_LIGHT_HEADER_META  "#94A3B8"

// ── CSS/report accent colors (not mirrored in Palette.js — C++ report only) ─────
#define APPC_CSS_TEAL_ACCENT         "#00bcd4"  // .analysis left-border
#define APPC_CSS_TEXT_DIM            "#8890a6"  // .meta text
#define APPC_CSS_TEXT_BRIGHT         "#e0e0e0"  // header target name

// ── Status icon (renderStatusIcon) — QColor RGB integer components ────────────
// 5WHY: QColor(QRgb) expects 0xAARRGGBB format — the top byte is alpha.
// Without the 0xFF prefix, alpha=0x00 making QColor fully transparent,
// which would render status icons invisible in HTML reports.
// 5WHY (2026-08-17 review): these 12 macros were hand-maintained literals that
// duplicated the palette status roles — a palette retune updated the string
// macros but silently left the RGB report icons stale.  Now DERIVED below.
{status_rgb}

// ── Progress bar thresholds ───────────────────────────────────────────────────
#define APPC_PROGRESS_BAR_BG         "#1E293B"  // track — always dark
"""


# Status roles rendered as RGB icons in HTML/PDF reports (renderStatusIcon).
# (macro stem, palette key) — values derived from the parsed palette at
# generation time so a palette retune propagates to the report icons.
RGB_ROLES = [
    ("SUCCESS", "success"),
    ("WARNING", "warning"),
    ("FAIL", "fail"),
    ("ERROR", "error"),
    ("SKIP", "skip"),
    ("INFO", "info"),
]


def _macro_stem(key: str) -> str:
    """camelCase → UPPER_SNAKE（与 ROLES 表命名一致）。"""
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", key).upper()


def _validate_roles(palettes: dict) -> None:
    """Fail with targeted messages when Palette.js and ROLES disagree.

    5WHY (review 2026-08-17): 两个方向的失配都被静默放过——新角色不加
    ROLES 时 --check 假通过（AppColors.h 缺少宏），删角色则 KeyError 裸
    traceback。白名单：textMuted（AppColors.h 故意的报告本地偏差）、
    scrim（8 位遮罩，无宏）。
    """
    excluded = {"textMuted", "scrim"}
    problems = []
    for theme in ("Dark", "Light"):
        for key in palettes[theme]:
            if key not in ROLES_KEYS and key not in excluded:
                problems.append(
                    f'Palette.js {theme}.{key} has no ROLES entry — add '
                    f'("{_macro_stem(key)}", "{key}") to ROLES in generate-appcolors.py')
    for key in ROLES_KEYS:
        for theme in ("Dark", "Light"):
            if key not in palettes[theme]:
                problems.append(
                    f'ROLES key "{key}" is missing from Palette.js {theme} '
                    f"— remove it from ROLES or restore the token")
    if problems:
        raise SystemExit("Palette.js ↔ ROLES mismatch:\n  " + "\n  ".join(problems))


def status_rgb_lines(palettes: dict) -> str:
    """0xAARRGGBB macro lines for the status RGB block (light + dark)."""
    out = []
    for stem, key in RGB_ROLES:
        light = palettes["Light"][key][1:]
        dark = palettes["Dark"][key][1:]
        out.append(f"#define APPC_{stem}_RGB{' ' * (30 - len(f'APPC_{stem}_RGB'))}0xFF{light}")
        out.append(f"#define APPC_{stem}_RGB_DARK{' ' * (30 - len(f'APPC_{stem}_RGB_DARK'))}0xFF{dark}")
    return "\n".join(out)


def build_header() -> str:
    palettes = parse_palette(read_palette())
    _validate_roles(palettes)
    out = [HEADER]

    def macro_line(stem: str, theme: str) -> str:
        key = ROLES_MAP[stem]
        value = palettes[theme][key].upper()
        return f"#define APPC_{stem}_{theme.upper():<30} \"{value}\""

    sections = [
        ("ACCENT ROLES (M3) — primary / secondary / tertiary / error + on-* pairs",
         [s for s, _ in ROLES if any(s.startswith(p) for p in
          ("PRIMARY", "ON_PRIMARY", "SECONDARY", "ON_SECONDARY", "TERTIARY", "ON_TERTIARY", "ERROR", "ON_ERROR"))]),
        ("NEUTRAL SURFACES (M3) — surface / on-surface / containers / outlines",
         [s for s, _ in ROLES if any(s.startswith(p) for p in
          ("SURFACE", "ON_SURFACE", "OUTLINE"))]),
        ("EXTENDED TOKENS — brand accent / text levels / status",
         [s for s, _ in ROLES if s in
          ("ACCENT", "TEXT_PLACEHOLDER", "SUCCESS", "WARNING", "WARNING_STRONG",
           "FAIL", "SKIP", "INFO", "TERMINAL_TEXT", "ON_SUCCESS_CONTAINER",
           "ICON_INK", "ON_FAIL", "ON_ACCENT_PAD")]),
    ]
    for title, stems in sections:
        out.append("// ═══════════════════════════════════════════════════════════════════════════════")
        out.append(f"// {title}")
        out.append("// ═══════════════════════════════════════════════════════════════════════════════")
        out.append("")
        if stems:
            out.append("// ── Dark palette ──────────────────────────────────────────────────────────────")
            for stem in stems:
                out.append(macro_line(stem, "Dark"))
            out.append("")
            out.append("// ── Light palette ─────────────────────────────────────────────────────────────")
            for stem in stems:
                out.append(macro_line(stem, "Light"))
            out.append("")

    out.append(TAIL.format(status_rgb=status_rgb_lines(palettes)))
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail (exit 1) if AppColors.h is out of date")
    args = ap.parse_args()

    generated = build_header()
    if args.check:
        if not APP_COLORS.exists():
            print("AppColors.h missing — run: python3 scripts/generate-appcolors.py")
            return 1
        current = APP_COLORS.read_text(encoding="utf-8")
        if current != generated:
            print("AppColors.h out of date — run: python3 scripts/generate-appcolors.py")
            return 1
        print("AppColors.h up to date ✓")
        return 0

    APP_COLORS.write_text(generated, encoding="utf-8")
    print(f"wrote {APP_COLORS.relative_to(ROOT)} from Palette.js")
    return 0


if __name__ == "__main__":
    sys.exit(main())
