#!/usr/bin/env python3
# =============================================================================
# generate-colored-icons.py — Pre-generate statically colored icon variants
# =============================================================================
# 5WHY (2026-08-01): Every runtime colorization mechanism failed on at least
# one platform (ShaderEffect inline GLSL: no Metal support; MultiEffect:
# QtQuick.Effects absent from iOS aqt; Image.color: property never existed;
# Rectangle overlay: unmasked foggy square).  Decision: NO runtime coloring
# at all.  This script bakes every palette color into a static SVG variant
# at build/commit time.  AppIcon.qml merely SELECTS a file (nearest palette
# color) and expresses alpha via Image.opacity — zero runtime colorization.
#
# Inputs:   src/Common/View/theme/Palette.js   (color roles, both themes)
#           resources/icons/ffffff/*.svg       (white-stroke master icons —
#                                               the ffffff variant doubles as
#                                               the white master set)
# Outputs:  resources/icons/<rrggbb>/<name>.svg
#           resources/resources_icons.qrc
#           src/Common/View/widgets/IconColors.js  (list for nearest-match)
#
# Run:      python scripts/generate-colored-icons.py
#           Re-run whenever Palette.js or resources/icons/ffffff/*.svg change.
#           (Enforced by scripts/pre-commit check.)
# =============================================================================
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PALETTE = ROOT / "src/Common/View/theme/Palette.js"
ICONS = ROOT / "resources/icons/ffffff"
OUT = ROOT / "resources/icons"
QRC = ROOT / "resources/resources_icons.qrc"
JS = ROOT / "src/Common/View/widgets/IconColors.js"


def palette_hexes() -> list[str]:
    text = PALETTE.read_text(encoding="utf-8")
    hexes = set(m.upper() for m in re.findall(r'"(#[0-9A-Fa-f]{6})"', text))
    hexes.add("#FFFFFF")  # master color, used by "white" callers
    hexes.add("#000000")  # ShadowIcon drop-shadow (alpha via Image.opacity)
    return sorted(hexes)


def main() -> None:
    hexes = palette_hexes()
    # Only white-stroke master icons are colorizable — multi-color art
    # would be corrupted by blind color replacement.
    icons = [p for p in sorted(ICONS.glob("*.svg"))
             if "#FFFFFF" in p.read_text(encoding="utf-8").upper()]
    if not icons:
        raise SystemExit("no master icons found in resources/icons/ffffff/")

    # Remove stale color-variant dirs (keep the ffffff master dir plus
    # non-color files like netanalysis.ico / netanalysis.png / app-icon.svg).
    for sub in sorted(OUT.iterdir()):
        if sub.is_dir() and re.fullmatch(r"[0-9a-f]{6}", sub.name) and sub.name != "ffffff":
            shutil.rmtree(sub)

    qrc_entries = []
    for hx in hexes:
        if hx == "#FFFFFF":
            # ffffff already exists as the white-stroke master set.
            sub = ICONS
        else:
            sub = OUT / hx[1:].lower()
            sub.mkdir(parents=True)
            for svg in icons:
                body = svg.read_text(encoding="utf-8")
                # Master icons are white-stroke (#FFFFFF).  Bake the target color.
                colored = body.replace("#FFFFFF", hx).replace("#ffffff", hx)
                out = sub / svg.name
                out.write_text(colored, encoding="utf-8", newline="\n")
        for svg in icons:
            qrc_entries.append(f"icons/{sub.name}/{svg.name}")

    qrc = ['<?xml version="1.0" encoding="utf-8"?>', "<RCC>", '    <qresource prefix="/">']
    qrc += [f"        <file>{e}</file>" for e in qrc_entries]
    qrc += ["    </qresource>", "</RCC>", ""]
    QRC.write_text("\n".join(qrc), encoding="utf-8", newline="\n")

    js = [
        "// AUTO-GENERATED by scripts/generate-colored-icons.py — DO NOT EDIT.",
        "// List of pre-generated icon colors for nearest-match selection.",
        ".pragma library",
        "var hexes = [",
    ]
    js += [f'    "{h}",' for h in hexes]
    js += ["];", ""]
    JS.write_text("\n".join(js), encoding="utf-8", newline="\n")

    print(f"generated {len(hexes)} colors x {len(icons)} icons = "
          f"{len(qrc_entries)} files")


if __name__ == "__main__":
    main()
