#!/usr/bin/env bash
# =============================================================================
# commit-screenshots.sh — Commit generated screenshots (+ README) back to master
# =============================================================================
# Used by the screenshots workflow's final commit job.  Copies freshly
# generated screenshots from the artifacts dir into the repo, then commits
# and pushes to master ONLY when something actually changed.
#
# Usage:
#   bash scripts/screenshot/commit-screenshots.sh <artifacts-dir>
#
#   <artifacts-dir> must contain the downloaded GitHub artifacts laid out as
#   resources/doc/screenshot/<platform>/<stage>.png (per-job uploads).
# =============================================================================
set -euo pipefail

ARTIFACTS="${1:?usage: commit-screenshots.sh <artifacts-dir>}"
ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

if [ ! -d "$ARTIFACTS" ]; then
    echo "[COMMIT] artifacts dir not found: $ARTIFACTS"
    exit 0
fi

# Copy any new screenshots into the repo (preserve resources/... layout).
# Artifact layout handled:
#   resources/doc/screenshot/<platform>/<stage>.png   → as-is
#   screenshots-<platform>/<stage>.png                → resources/doc/screenshot/<platform>/<stage>.png
#   doc/screenshot/ios/<size>/<stage>.png             → resources/doc/screenshot/ios/<size>/<stage>.png
# 5WHY: the first run committed nothing — upload-artifact@v4 flattens globbed
# files to the artifact root (no resources/ prefix), so files were copied to
# the repo ROOT and `git add resources/doc/screenshot` staged nothing.  Map
# by artifact-name/platform instead.
COPIED=0
while IFS= read -r png; do
    rel="${png#$ARTIFACTS/}"
    case "$rel" in
        resources/*)      dest="$ROOT/$rel" ;;
        screenshots-*)    dest="$ROOT/resources/doc/screenshot/${rel#screenshots-}" ;;
        doc/screenshot/*) dest="$ROOT/resources/$rel" ;;
        *)                dest="$ROOT/resources/doc/screenshot/$rel" ;;
    esac
    mkdir -p "$(dirname "$dest")"
    cp -f "$png" "$dest"
    COPIED=$((COPIED + 1))
done < <(find "$ARTIFACTS" -name '*.png' -type f 2>/dev/null || true)

echo "[COMMIT] copied $COPIED screenshot(s)"

git add resources/doc/screenshot README.md README_zh_CN.md README_zh_TW.md

if git diff --cached --quiet; then
    echo "[COMMIT] no changes to commit — skipping"
    exit 0
fi

git commit -m "docs: refresh platform screenshots via screenshot CI

Auto-generated by .github/workflows/screenshots-desktop.yml — real
OS-level captures of the production binary at each runtime stage."
# 5WHY: the commit job's push was rejected ('failed to push some refs') when a
# concurrent push landed after checkout — the workflow fires on every push to
# workflow/scripts paths, so it races with the developer pushing other commits.
# Fix: rebase onto the latest remote before pushing so our screenshot commit
# always sits on top.
git pull --rebase origin master
git push origin master
echo "[COMMIT] pushed"
