// =============================================================================
// AppColors.h — M3 semantic color roles (single source of truth for C++ colors)
//
// AUTO-GENERATED by scripts/generate-appcolors.py from
//   src/Common/View/theme/Palette.js — DO NOT EDIT THIS FILE.
//   Naming conventions are identical between C++ and QML:
//     C++:  APPC_PRIMARY_DARK / APPC_PRIMARY_LIGHT
//     QML:  Palette.Dark.primary / Palette.Light.primary
//
// Architecture (2026-08-17 M3 rename + simplify): Material 3 color roles —
//   primary/secondary/tertiary/error with on-* text pairs, surface + three
//   container levels, outline vs outlineVariant — plus NetDiagnostics
//   extended tokens.  Zero-consumer roles are deliberately absent (simplify
//   round 2026-08-17).  Exception: terminalText/onSuccessContainer are
//   QML-side semantic tokens tracked here for Palette.js↔AppColors.h sync
//   (a QML token leaving the sync net caused the dark textMuted divergence).
//   Color VALUES are unchanged from the pre-M3 palette —
//   5WHY: visual parity is a hard requirement of the rename; contrast
//   deviations are tracked by scripts/audit-palette-contrast.py instead of
//   being fixed here.
//
// KNOWN DEVIATION (pre-existing, report-local): APPC_TEXT_MUTED_* is #64748B
//   and intentionally NOT synced with Palette.js dark textMuted (#8494A8) —
//   the HTML report keeps its contrast-tuned text color.  Verified by
//   cmake/VerifyPaletteSync.cmake which deliberately skips textMuted.
// =============================================================================
#pragma once

// ═══════════════════════════════════════════════════════════════════════════════
// ACCENT ROLES (M3) — primary / secondary / tertiary / error + on-* pairs
// ═══════════════════════════════════════════════════════════════════════════════

// ── Dark palette ──────────────────────────────────────────────────────────────
#define APPC_PRIMARY_DARK                           "#60C8F8"
#define APPC_ON_PRIMARY_DARK                           "#0F172A"
#define APPC_PRIMARY_CONTAINER_DARK                           "#0C4A6E"
#define APPC_SECONDARY_DARK                           "#818CF8"
#define APPC_ON_SECONDARY_DARK                           "#0F172A"
#define APPC_TERTIARY_DARK                           "#68E5F4"
#define APPC_ON_TERTIARY_DARK                           "#0F172A"
#define APPC_ERROR_DARK                           "#F472B6"
#define APPC_ON_ERROR_DARK                           "#0F172A"

// ── Light palette ─────────────────────────────────────────────────────────────
#define APPC_PRIMARY_LIGHT                          "#0EA5E9"
#define APPC_ON_PRIMARY_LIGHT                          "#0F172A"
#define APPC_PRIMARY_CONTAINER_LIGHT                          "#E0F2FE"
#define APPC_SECONDARY_LIGHT                          "#6366F1"
#define APPC_ON_SECONDARY_LIGHT                          "#FFFFFF"
#define APPC_TERTIARY_LIGHT                          "#06B6D4"
#define APPC_ON_TERTIARY_LIGHT                          "#0F172A"
#define APPC_ERROR_LIGHT                          "#BE185D"
#define APPC_ON_ERROR_LIGHT                          "#FFFFFF"

// ═══════════════════════════════════════════════════════════════════════════════
// NEUTRAL SURFACES (M3) — surface / on-surface / containers / outlines
// ═══════════════════════════════════════════════════════════════════════════════

// ── Dark palette ──────────────────────────────────────────────────────────────
#define APPC_SURFACE_DARK                           "#0F172A"
#define APPC_ON_SURFACE_DARK                           "#F1F5F9"
#define APPC_ON_SURFACE_VARIANT_DARK                           "#94A3B8"
#define APPC_SURFACE_CONTAINER_LOW_DARK                           "#1E293B"
#define APPC_SURFACE_CONTAINER_DARK                           "#0F172A"
#define APPC_SURFACE_CONTAINER_HIGHEST_DARK                           "#334155"
#define APPC_OUTLINE_DARK                           "#64748B"
#define APPC_OUTLINE_VARIANT_DARK                           "#334155"

// ── Light palette ─────────────────────────────────────────────────────────────
#define APPC_SURFACE_LIGHT                          "#F8FAFC"
#define APPC_ON_SURFACE_LIGHT                          "#0F172A"
#define APPC_ON_SURFACE_VARIANT_LIGHT                          "#475569"
#define APPC_SURFACE_CONTAINER_LOW_LIGHT                          "#FFFFFF"
#define APPC_SURFACE_CONTAINER_LIGHT                          "#FFFFFF"
#define APPC_SURFACE_CONTAINER_HIGHEST_LIGHT                          "#F1F5F9"
#define APPC_OUTLINE_LIGHT                          "#64748B"
#define APPC_OUTLINE_VARIANT_LIGHT                          "#E2E8F0"

// ═══════════════════════════════════════════════════════════════════════════════
// EXTENDED TOKENS — brand accent / text levels / status
// ═══════════════════════════════════════════════════════════════════════════════

// ── Dark palette ──────────────────────────────────────────────────────────────
#define APPC_ACCENT_DARK                           "#FB7185"
#define APPC_TEXT_PLACEHOLDER_DARK                           "#64748B"
#define APPC_SUCCESS_DARK                           "#4ADE80"
#define APPC_WARNING_DARK                           "#F59E0B"
#define APPC_WARNING_STRONG_DARK                           "#EA580C"
#define APPC_FAIL_DARK                           "#F87171"
#define APPC_SKIP_DARK                           "#9CA3AF"
#define APPC_INFO_DARK                           "#A5B4FC"
#define APPC_TERMINAL_TEXT_DARK                           "#4ADE80"
#define APPC_ON_SUCCESS_CONTAINER_DARK                           "#4ADE80"
#define APPC_ICON_INK_DARK                           "#60C8F8"
#define APPC_ON_FAIL_DARK                           "#FFFFFF"
#define APPC_ON_ACCENT_PAD_DARK                           "#FFFFFF"
#define APPC_TERMINAL_INK_DARK                           "#60C8F8"

// ── Light palette ─────────────────────────────────────────────────────────────
#define APPC_ACCENT_LIGHT                          "#F43F5E"
#define APPC_TEXT_PLACEHOLDER_LIGHT                          "#94A3B8"
#define APPC_SUCCESS_LIGHT                          "#10B981"
#define APPC_WARNING_LIGHT                          "#EA580C"
#define APPC_WARNING_STRONG_LIGHT                          "#EA580C"
#define APPC_FAIL_LIGHT                          "#DC2626"
#define APPC_SKIP_LIGHT                          "#6B7280"
#define APPC_INFO_LIGHT                          "#2563EB"
#define APPC_TERMINAL_TEXT_LIGHT                          "#047857"
#define APPC_ON_SUCCESS_CONTAINER_LIGHT                          "#047857"
#define APPC_ICON_INK_LIGHT                          "#0C4A6E"
#define APPC_ON_FAIL_LIGHT                          "#FFFFFF"
#define APPC_ON_ACCENT_PAD_LIGHT                          "#FFFFFF"
#define APPC_TERMINAL_INK_LIGHT                          "#F8FAFC"

// ═══════════════════════════════════════════════════════════════════════════════
// REPORT-SPECIFIC COLORS (HTML/PDF report generation — report-local, static)
// ═══════════════════════════════════════════════════════════════════════════════

// ── Report-local text levels (see KNOWN DEVIATION header note) ────────────────
#define APPC_TEXT_MUTED_DARK           "#64748B"
#define APPC_TEXT_MUTED_LIGHT          "#64748B"

// ── Dark report theme ─────────────────────────────────────────────────────────
#define APPC_REPORT_DARK_BG_HEADER   "#0C4A6E"
#define APPC_REPORT_DARK_BG_SECTION  "#1E293B"
#define APPC_REPORT_DARK_BG_ROW_ALT  "#1E293B"
#define APPC_REPORT_DARK_BG_ROW      "#0F172A"
#define APPC_REPORT_DARK_BG_CARD_PASS "#16281b"
#define APPC_REPORT_DARK_BG_CARD_INFO "#141f33"
#define APPC_REPORT_DARK_BG_CARD_WARN "#2b2810"
#define APPC_REPORT_DARK_BG_CARD_FAIL "#2b1616"
#define APPC_REPORT_DARK_BG_CARD_SKIP "#1e1e2e"
#define APPC_REPORT_DARK_BORDER       "#334155"
#define APPC_REPORT_DARK_CODE_BG      "#0a0a14"
#define APPC_REPORT_DARK_CODE_FG      "#c0c0d0"
#define APPC_REPORT_DARK_DETAIL_BG    "#0f1629"
#define APPC_REPORT_DARK_FOOTER       "#5a5a72"
#define APPC_REPORT_DARK_HEADER_TARGET "#E2E8F0"
#define APPC_REPORT_DARK_HEADER_META  "#94A3B8"

// ── Light report theme ────────────────────────────────────────────────────────
#define APPC_REPORT_LIGHT_BG_HEADER  "#0F172A"
#define APPC_REPORT_LIGHT_BG_SECTION "#0F172A"
#define APPC_REPORT_LIGHT_BG_ROW_ALT "#F8FAFC"
#define APPC_REPORT_LIGHT_BG_ROW     "#FFFFFF"
#define APPC_REPORT_LIGHT_BG_CARD_PASS "#ECFDF5"
#define APPC_REPORT_LIGHT_BG_CARD_INFO "#EFF6FF"
#define APPC_REPORT_LIGHT_BG_CARD_WARN "#FFFBEB"
#define APPC_REPORT_LIGHT_BG_CARD_FAIL "#FEF2F2"
#define APPC_REPORT_LIGHT_BG_CARD_SKIP "#F1F5F9"
#define APPC_REPORT_LIGHT_BORDER      "#E2E8F0"
#define APPC_REPORT_LIGHT_CODE_BG     "#0F172A"
#define APPC_REPORT_LIGHT_CODE_FG     "#E2E8F0"
#define APPC_REPORT_LIGHT_DETAIL_BG   "#F8FAFC"
#define APPC_REPORT_LIGHT_FOOTER      "#94A3B8"
#define APPC_REPORT_LIGHT_HEADER_TARGET "#E2E8F0"
#define APPC_REPORT_LIGHT_HEADER_META  "#94A3B8"

// ── CSS/report accent colors (not mirrored in Palette.js — C++ report only) ─────
#define APPC_CSS_TEAL_ACCENT         "#00bcd4"  // .analysis left-border
#define APPC_CSS_TEXT_DIM            "#8890a6"  // .meta text
#define APPC_CSS_TEXT_BRIGHT         "#e0e0e0"  // header target name

// ── Status icon (renderStatusIcon) — QColor RGB integer components ────────────
// 5WHY: QColor(QRgb) expects 0xAARRGGBB format — the top byte is alpha.
// Without the 0xFF prefix, alpha=0x00 making QColor fully transparent,
// which would render status icons invisible in HTML reports.
// 5WHY (2026-08-17 review): these 12 macros were hand-maintained literals that
// duplicated the palette status roles — a palette retune updated the string
// macros but silently left the RGB report icons stale.  Now DERIVED below.
#define APPC_SUCCESS_RGB              0xFF10B981
#define APPC_SUCCESS_RGB_DARK         0xFF4ADE80
#define APPC_WARNING_RGB              0xFFEA580C
#define APPC_WARNING_RGB_DARK         0xFFF59E0B
#define APPC_FAIL_RGB                 0xFFDC2626
#define APPC_FAIL_RGB_DARK            0xFFF87171
#define APPC_ERROR_RGB                0xFFBE185D
#define APPC_ERROR_RGB_DARK           0xFFF472B6
#define APPC_SKIP_RGB                 0xFF6B7280
#define APPC_SKIP_RGB_DARK            0xFF9CA3AF
#define APPC_INFO_RGB                 0xFF2563EB
#define APPC_INFO_RGB_DARK            0xFFA5B4FC

// ── Progress bar thresholds ───────────────────────────────────────────────────
#define APPC_PROGRESS_BAR_BG         "#1E293B"  // track — always dark
